# Job Seeker Agent Configuration

# OpenAI Configuration
openai:
  api_key: null  # Set this or use OPENAI_API_KEY environment variable
  model: "gpt-4"  # or "gpt-3.5-turbo" for faster/cheaper results
  max_tokens: 2000
  temperature: 0.7

# Adzuna Job Board Configuration
adzuna:
  app_id: 876306e2  # Set this or use ADZUNA_APP_ID environment variable
  app_key: 7f16d3d0e5ca95494feba5ab8831cb59  # Set this or use ADZUNA_APP_KEY environment variable

# Jooble Job Board Configuration
jooble:
  api_key: a31c6058-400f-411d-a6f6-18992e2afaf0  # Set this or use JOOBLE_API_KEY environment variable

# Ollama Configuration  
ollama:
  url: "http://localhost:11434"
  model: "llama2"  # or any other model you have installed
  temperature: 0.3
  max_tokens: 2000

# Resume Settings
resume:
  template_path: "static/resume_template.html"
  output_directory: "data/output"
  default_resume_path: "data/resume.json"

# PDF Settings
pdf:
  enabled: true
  page_size: "Letter"
  margins:
    top: "0.75in"
    right: "0.75in"
    bottom: "0.75in"
    left: "0.75in"

# Job Search Preferences (these can be overridden at runtime)
job_preferences:
  location: null  # e.g., "San Francisco, CA" or "Remote"
  job_type: null  # e.g., "Full-time", "Part-time", "Contract"
  salary_range: null  # e.g., "$80k-$120k"
  remote_preference: null  # e.g., "Remote", "Hybrid", "On-site"
  industry: null  # e.g., "Technology", "Healthcare", etc.
  company_size: null  # e.g., "Startup", "Mid-size", "Enterprise"

# Application Settings
app:
  debug: false
  max_jobs_to_find: 7
  max_jobs_to_select: 5

